---
fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs-stdlib
      ref: 5.0.0
    epel:
      repo: stahnma-epel
      ref: 1.3.1
    apache:
      repo: puppetlabs-apache
      ref: 3.4.0
    httpauth:
      repo: jamtur01-httpauth
      ref: 0.0.3
    concat:
      repo: puppetlabs-concat
      ref: 5.0.0
