fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.12.0"
    epel:
      repo: "https://github.com/stahnma/puppet-module-epel"
      ref: "1.2.2"
    httpauth:
      repo: "https://github.com/jamtur01/jamtur01-httpauth"
    apache:
      repo: "https://github.com/puppetlabs/puppetlabs-apache"
      ref: "1.10.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
      ref: "2.2.0"
  symlinks:
    "nagios": "#{source_dir}"
